### ISSUE TITLE
Logo proposal for Mecene

### ISSUE THREAD

**Issue by radudangratian** [cryptohazard/mecene#1]
Hello! As we talked on Discord, here is the Logo and below you will find the link with the files

![asset 2-24](https://user-images.githubusercontent.com/34451833/38692703-514dcf9a-3e8d-11e8-8b92-95f8870642c0.png)

Gdrive:

https://drive.google.com/open?id=1HQeFmEMC-ouvitU5JlQBCXUrJRuS-8zp

**Comment by cryptohazard** [comment]
Thanks again for the cool logo!
